apps:
  - script: ./lib/index.js
    name: 'bot'
    watch: true
    env:
      NODE_ENV: development

      DISCORD_TOKEN: NzQ3MDM4NjQwNTcxNDE2NjY2.X0JD8w.MZw9rvgYF-sNI8H38F0Y1QYXkgk
      SHARDS_COUNT: 1

      RABBIT_URL: amqp://localhost
