export enum Syntax {
	EMPTY = '',
	CSS = 'css',
	ASCII = 'asciidoc',
	AHK = 'autohotkey',
	BASH = 'bash',
	COFFEE = 'coffeescript',
	CPP = 'cpp',
	CS = 'cs',
	DIFF = 'diff',
	FIX = 'fix',
	GLSL = 'glsl',
	INI = 'ini',
	JSON = 'json',
	MARKDOWN = 'md',
	ML = 'ml',
	PROLOG = 'prolog',
	PYTHON = 'py',
	XL = 'xl',
	XML = 'xml',
	YAML = 'yaml'
}
