name: Continuous Integration

on:
  push:
    branches: [main, develop, "release/*"]
    paths-ignore:
      - "**.md"
      - ".github/**"
      - ".vscode/**"
      - .dockerignore
      - .gitignore
      - LICENSE
  pull_request:
    branches: [main, develop, "release/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          check-latest: true

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install yarn
        run: |
          npm -g i yarn

      - name: npm install, build and test
        run: |
          yarn
          yarn build
          yarn test --noStackTrace

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: false
            verbose: true
