name: Sentry Deployment

on:
  push:
<<<<<<< HEAD
    branches:
      - main

jobs:
  sentryDeploy:
=======
    branches: [main]
    tags:
      - '*'

jobs:
  deploy:
>>>>>>> main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
<<<<<<< HEAD
          tagName: ${{ github.sha }}
=======
>>>>>>> main
          environment: production
